env:
  global:
  - secure: GJImxJSGHqav/AV6Z2+ZXv4yrUn6U4unS+fpRSqMAlm+PSFmHXKl/lg3ReerQb9fOPjBlEi0uzp29tLcTJSlQdtffAW1Yt2hZibvdW+7uA3K7Plypj1bcf6La2CVZi0UoEBcVOdaQJklsPYVXQW2/ZS3eS0I8EjPvYb+tNwlC0O4XnjTayi3YiCw0QJqrMFdbnqcdNaaK97uM4fIRxnUZq+QLvl0CJ5NRmGMaAsiP3dsWwqOav0rvzSuR4gv0yKelEbZKanK6eXMvsEMv7K8BRkmDkYyzRqzM/LfzEe7AfZSVuYVzDJEpnushY/FCM8z647IT+795KJIlnSYZDLj99ZOKuYwKmB3bgPIjMVQIvc43OVRGoeqYzlOTOnHzB+EnDvXPQ5n21eeodQEhCG0x+/QKiElgv5coS4WIWwp7YQRV/04mKuGe3OWwcS2yWPxS3Km8j7h2Rprq7P7r3g7o332HPDXW4MX2sg4t5Z78mAXNK+yULg+pmiG2OQMR+zN9GNIsUOvftDAWITe0akt9DCCdwYgb9lHjGJZh63OYhiC4gqzs/h4bnvxDJJh/CSgmjMW6zMvXpbqllquH/V+WUuMrkPy/hi7I2cSZ9XLMsJUJ+A8Xg4BrqsdNWDMni1chgOW8asSw0rZK4vOZ7QqXL1fjI7QryJh7aEWIo2Tvi4=
  - secure: JAe1RRvm06IT0NdcCcjlOYobAEMYgc4cQqeYfXVbG/1MTCzKs+SJKibDU89dN6M3RRzrCYjvtsYNE+BVOmlF+IZo3CjGeQCBquZ6QOW0WpdnRi4QrAK+Y/nCrCSNC5+PLFektsl9BnrXCm3XlgUdgijTF1ircjAWBZXilXXt+spXktiI/AyeskdX/608Zmi4EK49vGWd3//cyltC0hwumQ1ki6OZtr4YpmIk5oalTZ7pOc3FBh9kzqitn9F90VpAoagzsbLTOddSwVyCekCtn5XQ/TkCL9llqRahDQxQt71O0Ic3iKM4ukJU9ZHnBzwKyhqzEr8RZJamuaNgzLScn1RngQHZYfQJMH2XQRw9QOXLDeUNDNUGSC5cZeJSCCb9UZUC3ZBick1lTOk4ymKfinzOf7mF3mOihicr5TWqQvgnO2QS7iNxRtpbfbrI6Jo3lPoi9YIPBg9KbkgQrXuNV64oYXt0sZi+88dsjiFlwGnR3OJAapSLKThVX7R1IOyBQfJyzJQ9QNi2pXNeTJ74h7Vvpm59xhiji81bqSH9hIwZ336SJBN9VIawskKnJtdwyyN/Z8qXAawLVF1FmN+hWda/Awi6DPitPRzDUjtErVxL+dGRi8dp7mUh0KrFDE4cKYdkM1gIYMX7Q+Bb0GMkxtfbi7zvPQCSeixy8g4geng=
  - secure: hs4PiElurSGDTwRf0RAFjcvgym+GcCnKhw2WLvE/Rk4XNqyPQHZ4Fj34BL5aiNPEp/Qc8l9g6ToWvEINZkygV/pdsYOA4lM/eL8dk1ZI5j7JxTDDF8Rw1AxsOEyCRFeQgpXtq1xUzW69E77cxE67cJVlV0wCfhpqKKe0Sf6ERBXO++A6qkfohd4h2f8xJzw8ehKel7+c806Q+sSQnY0g5AgaFd9logFYl2NXxiVd9/j7xYFYfSvjTrfFmg8BxhVS+2X0mrdXlKfHtiai5IGfhjIfoIRk6A6yT8KR7WzWH4h1vHAIaXp1wu3nxhjDy1lY8jsc5ZrTNt6yHUasW5UOGQp8nVLdPC207htkFFHUxYlfIZaTq2eoO8GhaKbGGuqdWXXw9bjvds5wFYVt7GgEewQO6Z540h+49yxTseHtjp66VIvs7KCjNzR3gZyjsIqtofgyEpbi4A+PVi8q2Aka73rxNUMCKE6TGalZr+76CJGVZ73OPHujSKTDZrIO7R8G6MiUsXuHUHJVe6T6XNVM4hEH4VM5NI/p3H4Ve5Ur9K6I9JZSK4kWnFWyUmgekQ3ZHGMpn++RSx8+L2lhWhYf5/I+SVozt0ny69NYg6UA++fMKCG/mYlCMfIE8Owvq2EZWV8AaeeyQB2j/omPClj8nUQEolrb7M2kWaoUTGsBKo4=

language: python
sudo: required

services:
- docker

python:
- 3.9

cache:
  directories:
  - $HOME/.cache/pip

install:
- mkdir .build
- ln -s ~/virtualenv/python3.9 .build/venv
- make build

script:
- make check

after_success:
- make publish
